// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: followers.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const follow = `-- name: Follow :one
INSERT INTO followers (user_id, follower_id)
VALUES ($1, $2) RETURNING user_id, follower_id, created_at
`

type FollowParams struct {
	UserID     uuid.UUID
	FollowerID uuid.UUID
}

func (q *Queries) Follow(ctx context.Context, arg FollowParams) (Follower, error) {
	row := q.db.QueryRowContext(ctx, follow, arg.UserID, arg.FollowerID)
	var i Follower
	err := row.Scan(&i.UserID, &i.FollowerID, &i.CreatedAt)
	return i, err
}

const unfollow = `-- name: Unfollow :exec
DELETE
FROM followers
WHERE user_id = $1
  AND follower_id = $2
`

type UnfollowParams struct {
	UserID     uuid.UUID
	FollowerID uuid.UUID
}

func (q *Queries) Unfollow(ctx context.Context, arg UnfollowParams) error {
	_, err := q.db.ExecContext(ctx, unfollow, arg.UserID, arg.FollowerID)
	return err
}
