// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)


type Follower struct {
	UserID     uuid.UUID
	FollowerID uuid.UUID
	CreatedAt  time.Time
}



type User struct {
	ID        uuid.UUID
	Username  string
	Password  []byte
	Email     string
	CreatedAt time.Time
	IsActive  bool
	RoleID    int16
}

type UsersInvitation struct {
	Token  string
	UserID uuid.UUID
	Expiry time.Time
}

type UsersRole struct {
	ID          int16
	Name        string
	Level       int16
	Description string
}
