// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users_roles.sql

package database

import (
	"context"
)

const getById = `-- name: GetById :one
SELECT id, name, level, description
FROM users_roles
WHERE id = $1
`

func (q *Queries) GetById(ctx context.Context, id int16) (UsersRole, error) {
	row := q.db.QueryRowContext(ctx, getById, id)
	var i UsersRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Level,
		&i.Description,
	)
	return i, err
}

const getByRoleName = `-- name: GetByRoleName :one
SELECT id, name, level, description
FROM users_roles
WHERE name = $1
`

func (q *Queries) GetByRoleName(ctx context.Context, name string) (UsersRole, error) {
	row := q.db.QueryRowContext(ctx, getByRoleName, name)
	var i UsersRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Level,
		&i.Description,
	)
	return i, err
}
