

###
# group: comments
# @name Comments
POST {{posts}}/v1/comments
#User-Agent: Thunder Client (https://www.thunderclient.com)
Content-Type: application/json
#Accept: application/json

{
  "content": "comment-User0",
  "post_id": "354546f8-0960-4d54-93aa-5c14c5b57706"
}

###
# group: comments
# @name Comments By PostId
GET {{posts}}/v1/comments/354546f8-0960-4d54-93aa-5c14c5b57706
#User-Agent: Thunder Client (https://www.thunderclient.com)
Content-Type: application/json
#Accept: application/json

###
# @name health
GET {{posts}}/v1/health