# eegis

###
# group: post
# @name Post
POST {{posts}}/v1/posts
Content-Type: application/json
Accept: application/json

{
  "title": "post 2",
  "content": "content 2"
}

###
# group: post
# @name Post by ID
GET {{posts}}/v1/posts/54ce2b70-1b92-4992-9bb7-0306ec6644af
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJxb3JhYWxodWIiLCJleHAiOjk2Mjg0NjI2MzYsImlhdCI6MTc0MDQ3NDgwOCwiaXNzIjoicW9yYWFsaHViIiwibmJmIjoxNzQwNDc0ODA4LCJyb2xlIjp7IlZhbHVlIjoxLCJEZXNjcmlwdGlvbiI6InVzZXIifSwic3ViIjoiYzJlM2Y1OTUtZDM0NS00NGE0LWIzMzgtOTI3ZGY3ZGJjY2UzIn0.I6zFQEl45fwBO5JN02qJITQ167mOAiD1xF9HbDn1uMs


###
# group: post
# @name All POSTS
GET {{posts}}/v1/posts
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJxb3JhYWxodWIiLCJleHAiOjk2Mjc3OTczMzgsImlhdCI6MTczOTgwOTUxMSwiaXNzIjoicW9yYWFsaHViIiwibmJmIjoxNzM5ODA5NTExLCJyb2xlIjp7IlZhbHVlIjoxLCJEZXNjcmlwdGlvbiI6InVzZXIifSwic3ViIjoiYzJlM2Y1OTUtZDM0NS00NGE0LWIzMzgtOTI3ZGY3ZGJjY2UzIn0.nq3wCgfQjfFRsAbukiKhahmFQebIegFrauNkHRsX5w4

###
# group: post
# @name DELETE Post
DELETE {{posts}}/v1/posts/6701746e-d91b-492e-b980-1a82e194eaf1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJxb3JhYWxodWIiLCJleHAiOjE3MzU3NTE0NTAsImlhdCI6MTczNTQ5MjI1MCwiaXNzIjoicW9yYWFsaHViIiwibmJmIjoxNzM1NDkyMjUwLCJzdWIiOiIwZjcyNzA5NC0zMTRkLTQyODMtOWYwYi0xMDFmNmM5MDY1MjUifQ.ref7CJZ8KgF980dnXcx5HUb5v6Y1EiGi-P8_S0H9tLU

###
# group: post
# @name UPDATE Post
PUT {{posts}}/v1/posts/6701746e-d91b-492e-b980-1a82e194eaf1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJxb3JhYWxodWIiLCJleHAiOjk2Mjg1NjU3NjYsImlhdCI6MTc0MDU3NzkzOCwiaXNzIjoicW9yYWFsaHViIiwibmJmIjoxNzQwNTc3OTM4LCJyb2xlIjp7IlZhbHVlIjoyLCJEZXNjcmlwdGlvbiI6Im1vZGVyYXRvciJ9LCJzdWIiOiJjMmUzZjU5NS1kMzQ1LTQ0YTQtYjMzOC05MjdkZjdkYmNjZTMifQ.5kT3PK-B7sXonEt8AhWclyiYz9SkYVXXJaOXdxch-n8

{
 "tags": ["tag1"]

}


###
# group: post
# @name PUT moderation
PUT {{posts}}/v1/posts/54ce2b70-1b92-4992-9bb7-0306ec6644af/review
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJxb3JhYWxodWIiLCJleHAiOjk2Mjg1NjU3NjYsImlhdCI6MTc0MDU3NzkzOCwiaXNzIjoicW9yYWFsaHViIiwibmJmIjoxNzQwNTc3OTM4LCJyb2xlIjp7IlZhbHVlIjoyLCJEZXNjcmlwdGlvbiI6Im1vZGVyYXRvciJ9LCJzdWIiOiJjMmUzZjU5NS1kMzQ1LTQ0YTQtYjMzOC05MjdkZjdkYmNjZTMifQ.5kT3PK-B7sXonEt8AhWclyiYz9SkYVXXJaOXdxch-n8

{
  "status": "approved"

}