###
# group: auth
# @name CREATE USER
POST {{users}}/v1/auth/users
Content-Type: application/json
Accept: application/json

{
  "username": "user57",
  "email" : "user57@qoraalhub.com",
  "password": "password",
  "role_id": 1
}

###
# group: auth
# @name authenticate
POST {{users}}/v1/auth/token
Content-Type: application/json
Accept: application/json

{
  "email" : "user1@qoraal.com",
  "password": "password"
}

//result : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJxb3JhYWxodWIiLCJleHAiOjk2MjcwMjQ1NjgsImlhdCI6MTczOTAzNjc0MCwiaXNzIjoicW9yYWFsaHViIiwibmJmIjoxNzM5MDM2NzQwLCJyb2xlIjp7IlZhbHVlIjoyLCJEZXNjcmlwdGlvbiI6Im1vZGVyYXRvciJ9LCJzdWIiOiIwZjcyNzA5NC0zMTRkLTQyODMtOWYwYi0xMDFmNmM5MDY1MjUifQ.i0U9HdgpcAFrFBTW8wE1JgwmLQQ8ca1N_UnpbiZil6U


