###
# group: auth
# @name CREATE USER
POST {{users}}/v1/auth/users
Content-Type: application/json
Accept: application/json

{
  "username": "user57",
  "email" : "user57@qoraalhub.com",
  "password": "password",
  "role_id": 1
}

###
# group: auth
# @name authenticate
POST {{users}}/v1/auth/token
Content-Type: application/json
Accept: application/json

{
  "email" : "user1@qoraal.com",
  "password": "password"
}


