// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID        uuid.UUID
	Content   string
	PostID    uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
}

type Post struct {
	ID        uuid.UUID
	Title     string
	Content   string
	CreatedAt time.Time
	UserID    uuid.UUID
	Tags      []string
	Version   int32
}
